version: '3.8'

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./fuelcms:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: .
      # context: .
      # dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./fuelcms:/var/www/html:delegated
    depends_on: 
      - mysql
    environment: 
      DATABASE_NAME: fuel
      DATABASE_USER: fuel
      DATABASE_PASSWORD: secret
      DATABASE_HOST: mysql
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes: 
      - ./fuelcms/fuel/install:/install
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on: 
      - mysql